#!/usr/bin/env ruby
require "franklin"

require "optparse"
# options = {}
parser = OptionParser.new { |opts|
  opts.banner = "Usage: frankling [options] search terms"

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    puts "Franklin v#{Franklin::VERSION}"
    exit
  end
}

parser.parse!

begin
  Franklin.run(ARGV.join(" "), out: STDOUT)
rescue ArgumentError => ex
  puts <<-ERROR.gsub(/^  /, "")
  Oops! #{ex.message}
  #{parser}
  ERROR
rescue Errno::ENOENT
  puts <<-ERROR.gsub(/^  /, "")
  Oops! It looks like you have not configured franklin
  Please add a configuration file in $HOME/.franklin that looks like this:
  ---
  :libraries:
    - :name: San Francisco Public Library
      :url: http://sfpl.lib.overdrive.com
    - :name: San Diego Public Library
      :url: http://sdpl.lib.overdrive.com
  ERROR
end
