#!/usr/bin/env ruby
require "franklin"
require "optparse"

options = { out: STDOUT, config_path: Franklin::Config::DEFAULT_CONFIG_FILE }
parser = OptionParser.new { |opts|
  opts.banner = "Usage: frankling [options] search_term1 search_term2..."

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    puts "Franklin v#{Franklin::VERSION}"
    exit
  end

  opts.on("--config-path=CONFIG", "Path to configuration file. Defaults to ~/.franklin") do |config_path|
    options[:config_path] = config_path
  end

  opts.on "-tTYPE", "--type=TYPE", "Filter results by type (eBook, Audiobook, etc). Will override config" do |type|
    options[:type] = type
  end
}

parser.parse!

begin
  Franklin.run(ARGV.join(" "), options)
rescue ArgumentError => ex
  STDERR.puts <<-ERROR.gsub(/^  /, "")
  Oops! #{ex.message}
  #{parser}
  ERROR
rescue Errno::ENOENT
  STDERR.puts <<-ERROR.gsub(/^  /, "")
  Oops! It looks like you have not configured franklin
  Please add a configuration file in $HOME/.franklin that looks like this:
  ---
  libraries:
    - name: San Francisco Public Library
      url: http://sfpl.lib.overdrive.com
    - name: San Diego Public Library
      url: http://sdpl.lib.overdrive.com
  default_type: eBook # Optional, leave empty to search for all types
  ERROR
end
